### ISSUE TITLE
Some issues about this project.

### ISSUE THREAD

**Issue by LiuTingWed** [ags3927/MERGE#1]
Hi Aniruddha!

You are really do a great job！As a rookie for the ST dataset, I appreciate you upload the ST datasets in Google Driver. That's HELP ME A LOT. 👍 

But I meet some problems when running this project.

No.1.  I guess the order of operation of mode is cnn_train -> cnn_test -> gnn_train -> gnn_test. When I run cnn_test mode.  I find some bug in these codes in blow:

![Image](https://github.com/user-attachments/assets/43285d0d-c119-43cd-9122-50cdf99e120e)

(1) **len(data['slides'])** return int type. I guess the logic of this code is to skip the slides used for training, assign the model prediction results (preds) to the array of the corresponding slide according to the non-zero position, and save it as a .npy file. But when I correct to **rang(len(data['slides']))**, it will raise a **corrupted double-linked list (not small) error**. I can't figure out, so i just delete these code to next mode. 

No.2.  When change mode is gnn_train. Using the following code will cause an error of CUDA memory.

![Image](https://github.com/user-attachments/assets/267e7640-ceeb-48e2-b7a2-df9854f3671f)

Please wrap the loop with **with torch.no_grad():**

No.3. Do you miss some config for the Building the hierarchical graph? I can't find some cluster configs in the project.

![Image](https://github.com/user-attachments/assets/df6c41b4-fa6d-4157-a22c-77b314c44da0)

Looking forward your reply.

**Comment by ags3927** [comment]
Made multiple commits to fix all the issues. Please check if the newest version is fully functional. The commit messages have explanations on what bugs I fixed.

- Commits 9be7158f89cacaa013b10dd6b8a02223cdf829ad to 72c1c1d8820a8b1b281ea89cd8821d45f335e0c1 solves No. 1 
- Commit 4d043477f5d055b94dd12f480d7ceefc17436b4a solves No. 2
- Commits ab644d4effc10f8c5907004bf99c8cf44fad1c37 to 9f1abc9328269fe357eca3ab032e6d6e876636b7 solves No. 3 and a few other issues

**NB: Each bug commit details the bug(s) and their fixes**

**Comment by LiuTingWed** [comment]
Thanks l lot. I will enjoy it

**Comment by LiuTingWed** [comment]
Hi Aniruddha! 
Your commits work! But I still get Value Error when I run mode=gnn_train.
Here is my reports:

![Image](https://github.com/user-attachments/assets/1687adfe-8a05-440c-ae6a-26c5e337d88e)

Additionally, I have some question about the cross validation. In the paper,  8 folds cross validation performs, but I find actually the cross validation of code is 8th fold rather than 8 folds. Am I right?

![Image](https://github.com/user-attachments/assets/87727c48-c1e3-48a8-9b8c-c901edde727b)

The logic of this code seems to involve randomly splitting the training and validation sets, but it doesn't address the data leakage issue mentioned in TRIDENT, which states that data from the same patient should not appear in both the training and validation sets. I think this is a reasonable concern, but I don't see any handling of this issue in the code. How do you think this problem?

**Comment by ags3927** [comment]
For the shape mismatch, could you also provide the config file? What dataset are you running this on?

<hr>

Yes, a single run of the model will only validate for a single fold. You have to change the fold in each run (set using the parameter --fold for the main.py file).

<hr>

With regards to the cross-validation issue you mentioned, I personally think that as we are approaching the phase where we have large ST cohorts (like [Hest1k](https://arxiv.org/abs/2406.16192)), we should stop considering the usage of multiple samples from the same patient as 'data leak'. The reason I say this is that the only reason prior methods had to account for this issue is because they had stringently small training sets.

I think the biggest issue stems from people using a small training set where multiple samples from a single patient are consecutive slices of tissue (you may think of it as slices of bread in a packet that are adjacent to each other - haha). Biologically speaking, if that happens, then you may end up with a similar data distribution (still not always the case). If your samples from the same patient are not consecutive slices of tissue (to keep the same analogy as before - they are slices of bread that are not adjacent), then it is likely that they won't have highly overlapping distributions.

I think the concern shown by prior methods used to be a valid one, but biologically speaking it has gotten less and less relevant as we have larger cohorts of data and more diverse samples.

**Comment by LiuTingWed** [comment]
Hi Aniruddha! 
Your response has resolved my confusion. Thank you very much.
I run this project on her2st. The config files as following:

![Image](https://github.com/user-attachments/assets/2c74da27-03c1-4e52-9ff4-1e1657ef9e82)

**Comment by ags3927** [comment]
Ok, so I don't have a custom collate function and the code can't handle multi worker dataloader setup. I have not dug deep enough into the issue to really understand what is going on here. But setting num_workers=0 for the graph dataloaders [here](https://github.com/ags3927/MERGE/blob/be8f19a988e0d8240bb7096090847ffd1833f078/utils/graph.py#L209) seems to work.

I pushed the commit be8f19a988e0d8240bb7096090847ffd1833f078 to change that. If I get time I will later look into what is messing with the collation and maybe write a custom collate function to work with multiple workers in the dataloader.

**Comment by LiuTingWed** [comment]
Hi Aniruddha!

Thank you for your patient reply. I think the code that caused the shape mismatch error does not affect the performance testing of the second-stage model, so I deleted it.

In graph.py at line 210, val_dataloader is being passed train_dataset. Is this a bug?

Another question is about the performance of the second-stage GNN. I followed the configuration mentioned above and trained it on the Her2st dataset. I found that the performance of the first-stage CNN was not bad, but the performance of the GNN was very poor, whether in the eighth fold validation or in cross-validation.  Any idea?

![Image](https://github.com/user-attachments/assets/74b3fdb5-d150-4d62-aae9-5a495367026e)

![Image](https://github.com/user-attachments/assets/58cc86fe-f645-476c-b85d-ff7ecd47521b)

**Comment by ags3927** [comment]
Hi, you are correct about the bug for the dataloader. I fixed it in commit d4be4fa5895d92a21008bb6a9924c156a23ba0d0.
<hr>

As for the performance issue, that seems very strange. The model also seems to be converging slowly, but nowhere near CNN performance (which seems good). Can you try increasing the epoch count?

Originally I trained the model by processing the entire graph for the whole dataset in a single batch. The current code only processes one sample per batch. Maybe that can be a contributing factor for slow convergence?

I changed the code to sample-by-sample processing because not everyone might have the resource to train using the whole dataset level graph at once.

I am going to re-run the experiments myself and report back here as soon as I have the time.

**Comment by LiuTingWed** [comment]
Hi Aniruddha! 

Thank you again for your patient reply.  

I have followed your suggestion to increase the training epoch for the GNN to 800, but the results still fall short of expectations. It occurs to me that the issue you mentioned (Originally I trained the model by processing the entire graph for the whole dataset in a single batch.) might be the culprit. I would really like to cite your work in my own work.  Could you provide the version of the entire graph code?

Another question is the Table 1 of your paper, the ResNet + FCN method, which is a relatively basic approach, is presented in the first row of the comparison. I am wondering why it performs better than the other methods in the table, including the TRIPLEX method from CVPR 2024. 

Looking forward your reply.

**Comment by ags3927** [comment]
Hi, I have made a few commits (last commit b643cf20de351f531fcf77557f9ebc7d7712f6af) adding the whole dataset level codes.

In the main.py file ([from this line](https://github.com/ags3927/MERGE/blob/b643cf20de351f531fcf77557f9ebc7d7712f6af/main.py#L53)) there are a few lines for graph construction and gnn training which are commented out. You need to un-comment those and then comment out the next two lines which do not have "_whole_dataset" in the function names.

<HR>

Regarding your question about why the ResNet + FCN performs so well, I think because we re-train the whole ResNet18 on the dataset, it overfits the network to this. I remember experimenting with a Visium v2 sample from the 10x genomics website, the ResNet + FCN performed very poorly on the external test sample, but all the complex baselines as well as my method performed well.
